[package]
name = "quamatic/rbx-react-redux"
description = "React bindings for Roblox Redux."
version = "1.0.0"
license = "MIT + Apache 2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "core-packages/react@17.0.1-rc.19"
ReactRoblox = "core-packages/react-roblox@17.0.1-rc.19"
Redux = "quamatic/rbx-redux@^1.0.0"